use fst::Map;
use lazy_static::lazy_static;
use std::{os::unix::ffi::OsStrExt, path::Path};

lazy_static! {
    static ref FILENAME_ICONS: Map<&'static [u8]> = {
        const FILENAME_ICONS_BYTES: &[u8] =
            include_bytes!(concat!(env!("OUT_DIR"), "/filename_icons.bin"));

        // Safety: the bytes are correctly generated by fst in the build script, so we can use `unwrap_unchecked`
        unsafe { Map::new(FILENAME_ICONS_BYTES).unwrap_unchecked() }
    };
    static ref EXT_ICONS: Map<&'static [u8]> = {
        const EXT_ICONS_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/ext_icons.bin"));

        // Safety: the bytes are correctly generated by fst in the build script, so we can use `unwrap_unchecked`
        unsafe {
            Map::new(EXT_ICONS_BYTES).unwrap_unchecked()
        }
    };
    static ref FOLDER_ICONS: Map<&'static [u8]> = {
        const FOLDER_ICONS_BYTES: &[u8] =
            include_bytes!(concat!(env!("OUT_DIR"), "/folder_icons.bin"));

        // Safety: the bytes are correctly generated by fst in the build script, so we can use `unwrap_unchecked`
        unsafe { Map::new(FOLDER_ICONS_BYTES).unwrap_unchecked() }
    };
}

pub fn get_icon_for_file(path: impl AsRef<Path>) -> Option<u64> {
    let path = path.as_ref();
    let basename = path.file_name().unwrap();

    FILENAME_ICONS.get(basename.as_bytes()).or_else(|| {
        let ext = path.extension().unwrap();

        EXT_ICONS.get(ext.as_bytes())
    })
}

pub fn get_icon_for_folder(path: impl AsRef<Path>) -> Option<u64> {
    let path = path.as_ref();
    let basename = path.file_name().unwrap();

    FOLDER_ICONS.get(basename.as_bytes())
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn common_languages() {
        assert_eq!(get_icon_for_file("./test.js"), Some(296));
        assert_eq!(get_icon_for_file("./test.ts"), Some(633));
        assert_eq!(get_icon_for_file("./test.jsx"), Some(508));
        assert_eq!(get_icon_for_file("./test.tsx"), Some(529));
        assert_eq!(get_icon_for_file("./test.json"), Some(284));
        assert_eq!(get_icon_for_file("./test.yaml"), Some(708));
        assert_eq!(get_icon_for_file("./test.yml"), Some(708));
        assert_eq!(get_icon_for_file("./test.md"), Some(361));
        assert_eq!(get_icon_for_file("./test.css"), Some(116));
        assert_eq!(get_icon_for_file("./test.html"), Some(255));
        assert_eq!(get_icon_for_file("./test.rs"), Some(525));
    }

    #[test]
    fn common_folders() {
        assert_eq!(get_icon_for_folder("./.github"), Some(862));
        assert_eq!(get_icon_for_folder("./src"), Some(1054));
        assert_eq!(get_icon_for_folder("./tests"), Some(1084));
    }
}
